### ISSUE TITLE
Can the monitor work with RAKv2? I didn't see it on the pick-list.

### ISSUE THREAD

**Issue by NickDatLe** [nhatfield/hnt_monitor#35]
Only options were Bobcat, LongAP, Nebra, and SenseCap. I did not see a RAK option. Is it there and I'm just not seeing it?

**Comment by nhatfield** [comment]
Rack is not supported @NickDatLe ... They do not have an API available for use to pull metrics from like the other miners do unfortunately. If you can, it would be great to get them to add an API so we can collect metrics. Mention it as much as possible and get the community to jumpstart the devs into providing an endpoint on the miner we can collect from. The only requirement is that the diag payload is in JSON format

**Comment by nhatfield** [comment]
Closing this one out until the vendor can get us an endpoint to scrape metrics from
