### ISSUE TITLE
docker software install as root only when needed. 

### ISSUE THREAD

**Issue by Jackie4cincinnatus4group** [nhatfield/hnt_monitor#40]
The docker.io needs to be installed as root but if the parts that don't need root could be installed as none root it would make things more secure.

**Comment by nhatfield** [comment]
Which parts are you referring to? Docker should be the only thing getting installed except on Mac OS there is an addition of GNU sed using brew.

**Comment by nhatfield** [comment]
Going to mark this as closed since there has been no comment from the OP. Also this install will run as which ever user you give access to to run it.
