### ISSUE TITLE
Add support for hnt_monitor on Raspberry Pi

### ISSUE THREAD

**Issue by romi2002** [nhatfield/hnt_monitor#44]
Centos does not have official support for the epel repo, so [this](https://wiki.centos.org/SpecialInterestGroup/AltArch/armhfp#How_Can_I_Enable_EPEL_7_on_armhfp_.3F) workaround has to be done in order to build the docker image for ARM platforms.

**Comment by nhatfield** [comment]
This is done in 7.10.0
