### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by GeerGuy** [nhatfield/hnt_monitor#69]
Raspberry Pi 4 with newest OS.

Error Message:
Complete!
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.osuosl.org
 * centos-kernel: mirror.12z.eu
 * extras: ftp.osuosl.org
 * updates: ftp.osuosl.org
No package epel-release available.
Error: Nothing to do
ERROR: Service 'hnt_monitor' failed to build: The command '/bin/sh -c yum update -y  && yum -y install epel-release  && yum update -y  && yum install -y jq  && mkdir -p /opt/hnt_monitor  && rm -rf /tmp/*  && yum clean all -y' returned a non-zero code: 1
root@raspberrypi:/home/pi/hnt_monitor#

**Comment by nhatfield** [comment]
@GeerGuy there's no support for pi at the moment

**Comment by GeerGuy** [comment]
OK, you might want to make that clear.  It looks great and I hope that it will work with Pi's soon.  Thanks

**Comment by nhatfield** [comment]
Added to the README: https://github.com/nhatfield/hnt_monitor/blob/master/README.md#system-requirements 

Does grafana and prometheus all stand up ok on the PI ? I have not been able to test the full stack on a PI yet so Im not sure what all is broken there. I do know that the hnt monitor images cannot build or run there, but can the other supporting containers run ok? 

Thanks!

**Comment by GeerGuy** [comment]
Yes, Grafana and Prometheus run fine on a Pi.

**Comment by nhatfield** [comment]
Awesome thanks for the feedback. I updated the doc so it is clear going forward. Closing this ticket since I already have an open enhancement for this: https://github.com/nhatfield/hnt_monitor/issues/44
