### ISSUE TITLE
SenseCAP Block Height is incorrect

### ISSUE THREAD

**Issue by mdaviesnz** [nhatfield/hnt_monitor#80]
Block height for Sensecap seems to show the blockchain height, not the synced height of a hotspot. 

In the API Docs (https://status-api-doc.sensecapmx.cloud/) in the device detail request there's a separate field for Block height of device (called 'height') and another for the height of the blockchain (called 'totalHeight'), looks like the monitoring might be reading the latter field.

**Comment by nhatfield** [comment]
@mdaviesnz  we are using `.data.height` not totalheight... the source code is here: https://github.com/nhatfield/hnt_monitor/blob/develop/src/lib/sensecap#L54

Which is defined here: https://github.com/nhatfield/hnt_monitor/blob/develop/src/lib/sensecap#L33

the 9th column (starting from 0) is `.data.height`
