### ISSUE TITLE
Rocky Linux - Centos Docker Installation 

### ISSUE THREAD

**Issue by Remus-Catrina** [nhatfield/hnt_monitor#82]
It looks like while Installing on Rocky Linux docker compose does not get found in the repos.

Nice work around is the following:

1. $ sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
2. $ sudo chmod +x /usr/local/bin/docker-compose
3. $ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
 
Source: https://tastethelinux.com/install-docker-and-docker-compose-on-rocky-linux-8/

**Comment by nhatfield** [comment]
@Remus-Catrina this is for the installation of dependencies, yea? If so... 
* what is the package manager? (yum, apt-get,etc) 
* what is the output of `uname -a`
* what is the output of `cat /etc/os-release`

Thanks

**Comment by Remus-Catrina** [comment]
@nhatfield Yup for the installation of dependencies. 

Q: what is the package manager? (yum, apt-get,etc)
A: Yum 
Q: what is the output of uname -a
A: 
Linux localhost.localdomain 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 20:49:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Q: what is the output of cat /etc/os-release
A:
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"

Cheers

**Comment by nhatfield** [comment]
Closing this one out, community version is feature driven by the community. Please submit a pr if you wish to contribute for all
