### ISSUE TITLE
hnt_miner_reward_earned

### ISSUE THREAD

**Issue by feraldruid22** [nhatfield/hnt_monitor#87]
This is not related to the grafana but the prometheus unless the API is giving back false data.

First of:

hnt_miner_reward_earned_1d is correct

however the 7d and 30d showing the exact same value which would be only true if I would just setup the miner not long ago.

How are these windows working then? Like my current daily reward is 0.06 HNT, according to the explorer my 7d is 0.5 HNT and  the 30D is 1.8 HNT whilst with your metrics I get:

hnt_miner_reward_earned_1d 0.06

hnt_miner_reward_earned_7d 0.06

hnt_miner_reward_earned_30d 0.06

Now things gets more odd with the hnt_miner_reward_1d 7d 30d, I don't know what this supposed to display but I get 5 for all, even my overall HNT earnings are not 5.

**Comment by ubiru** [comment]
are these metrics all gone now?

**Comment by nhatfield** [comment]
resolve in release 7.10.0
